/*******************************************************************************
 *    This file was autogenerated by hostname.sh on 2010-07-15 12:17:31+02:00.
 *    Do not modify this file!
 *******************************************************************************/
#ifndef _HOSTNAME_H
#define _HOSTNAME_H

#ifndef HOSTNAME
#define HOSTNAME "tinyos"
#endif

#endif
