/*******************************************************************************
 *    This file was autogenerated by hostname.sh on 2010-07-13 16:58:09+02:00.
 *    Do not modify this file!
 *******************************************************************************/
#ifndef _HOSTNAME_H
#define _HOSTNAME_H

#ifndef HOSTNAME
#define HOSTNAME "telosb"
#endif

#endif
