/*******************************************************************************
 *    This file was autogenerated by hostname.sh on 2010-07-27 17:45:57+02:00.
 *    Do not modify this file!
 *******************************************************************************/
#ifndef _HOSTNAME_H
#define _HOSTNAME_H

#ifndef HOSTNAME
#define HOSTNAME "Linux 2.6.32-23-generic i686"
#endif

#endif
