#ifndef _MOTECOMM_SIZES_H
#define _MOTECOMM_SIZES_H

#define HD_BYTES_FROM_BITS(bits) (((bits) + 7) & ~7)

#define MCP_HD_VERSION 4
#define MCP_HD_HEADER  4
#define MCP_HD_IDENT   8
#define MCP_HD_TYPE    8
#define MCP_HD_PORT    8
#define MCP_HD_PAYLOAD 24

#define MCP_HEADER_BITS (MCP_HD_VERSION+MCP_HD_HEADER+MCP_HD_IDENT+MCP_HD_TYPE+MCP_HD_PORT+MCP_HD_PAYLOAD)
#define MCP_HEADER_BYTES HD_BYTES_FROM_BITS(MCP_HEADER_BITS)

#define MCP_TYPE_SIZE 256

#endif
